"""empty message

Revision ID: 9a418a9fb7ae
Revises: 
Create Date: 2026-10-03 13:11:18.099643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a418a9fb7ae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('google_id', sa.String(), nullable=True),
    sa.Column('auth_provider', sa.String(), nullable=False),
    sa.Column('age_consent', sa.Boolean(), nullable=False),
    sa.Column('terms_policy_accepted', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_google_id'), ['google_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('storage_accounts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('provider_account_id', sa.String(length=256), nullable=False),
    sa.Column('provider_account_email', sa.String(length=256), nullable=True),
    sa.Column('display_name', sa.String(length=256), nullable=True),
    sa.Column('encrypted_refresh_token', sa.Text(), nullable=True),
    sa.Column('root_folder_id', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('status_message', sa.String(length=256), nullable=True),
    sa.Column('total_bytes', sa.BigInteger(), nullable=False),
    sa.Column('used_bytes', sa.BigInteger(), nullable=False),
    sa.Column('reserved_bytes', sa.BigInteger(), nullable=False),
    sa.Column('allocated_limit_bytes', sa.BigInteger(), nullable=True),
    sa.Column('app_used_bytes', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('storage_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_storage_accounts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_storage_accounts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_storage_accounts_user_id'), ['user_id'], unique=False)

    op.create_table('virtual_folders',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('starred', sa.Boolean(), nullable=False),
    sa.Column('shared', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['virtual_folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('virtual_folders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_virtual_folders_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_virtual_folders_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_virtual_folders_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_virtual_folders_user_id'), ['user_id'], unique=False)

    op.create_table('folder_permissions',
    sa.Column('folder_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['virtual_folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('folder_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_folder_permissions_folder_id'), ['folder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_folder_permissions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_folder_permissions_user_id'), ['user_id'], unique=False)

    op.create_table('virtual_files',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('folder_id', sa.UUID(), nullable=True),
    sa.Column('starred', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['virtual_folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('virtual_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_virtual_files_folder_id'), ['folder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_virtual_files_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_virtual_files_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_virtual_files_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_virtual_files_user_id'), ['user_id'], unique=False)

    op.create_table('file_chunks',
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('storage_account_id', sa.UUID(), nullable=True),
    sa.Column('target_account_id', sa.UUID(), nullable=True),
    sa.Column('chunk_index', sa.BigInteger(), nullable=False),
    sa.Column('offset', sa.BigInteger(), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('provider_file_id', sa.String(length=256), nullable=True),
    sa.Column('upload_session_uri', sa.Text(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['virtual_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['storage_account_id'], ['storage_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_account_id'], ['storage_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_chunks_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_chunks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_chunks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_chunks_storage_account_id'), ['storage_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_chunks_target_account_id'), ['target_account_id'], unique=False)

    op.create_table('upload_sessions',
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('total_chunks', sa.BigInteger(), nullable=False),
    sa.Column('completed_chunks', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['virtual_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('upload_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upload_sessions_file_id'), ['file_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_upload_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_upload_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_upload_sessions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upload_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_upload_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_upload_sessions_id'))
        batch_op.drop_index(batch_op.f('ix_upload_sessions_file_id'))

    op.drop_table('upload_sessions')
    with op.batch_alter_table('file_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_chunks_target_account_id'))
        batch_op.drop_index(batch_op.f('ix_file_chunks_storage_account_id'))
        batch_op.drop_index(batch_op.f('ix_file_chunks_status'))
        batch_op.drop_index(batch_op.f('ix_file_chunks_id'))
        batch_op.drop_index(batch_op.f('ix_file_chunks_file_id'))

    op.drop_table('file_chunks')
    with op.batch_alter_table('virtual_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_virtual_files_user_id'))
        batch_op.drop_index(batch_op.f('ix_virtual_files_status'))
        batch_op.drop_index(batch_op.f('ix_virtual_files_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_virtual_files_id'))
        batch_op.drop_index(batch_op.f('ix_virtual_files_folder_id'))

    op.drop_table('virtual_files')
    with op.batch_alter_table('folder_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_folder_permissions_user_id'))
        batch_op.drop_index(batch_op.f('ix_folder_permissions_id'))
        batch_op.drop_index(batch_op.f('ix_folder_permissions_folder_id'))

    op.drop_table('folder_permissions')
    with op.batch_alter_table('virtual_folders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_virtual_folders_user_id'))
        batch_op.drop_index(batch_op.f('ix_virtual_folders_parent_id'))
        batch_op.drop_index(batch_op.f('ix_virtual_folders_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_virtual_folders_id'))

    op.drop_table('virtual_folders')
    with op.batch_alter_table('storage_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_storage_accounts_user_id'))
        batch_op.drop_index(batch_op.f('ix_storage_accounts_status'))
        batch_op.drop_index(batch_op.f('ix_storage_accounts_id'))

    op.drop_table('storage_accounts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_google_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
